const LogEventTypes = {
  MEMBER_JOIN: 'MEMBER_JOIN',
  MEMBER_LEAVE: 'MEMBER_LEAVE',
  MEMBER_KICK: 'MEMBER_KICK',
  MEMBER_BAN: 'MEMBER_BAN',
  MEMBER_UNBAN: 'MEMBER_UNBAN',

  MEMBER_TIMEOUT_ADD: 'MEMBER_TIMEOUT_ADD',
  MEMBER_TIMEOUT_REMOVE: 'MEMBER_TIMEOUT_REMOVE',

  MESSAGE_EDIT: 'MESSAGE_EDIT',
  MESSAGE_DELETE: 'MESSAGE_DELETE',
  MESSAGE_DELETE_BULK: 'MESSAGE_DELETE_BULK',

  INVITE_CREATE: 'INVITE_CREATE',
  INVITE_DELETE: 'INVITE_DELETE',

  VRC_LINKED: 'VRC_LINKED',
  VRC_UNLINKED: 'VRC_UNLINKED',

  NOTE_DELETED: 'NOTE_DELETED'
}

export default LogEventTypes